// Built-in thesis library. Users add any of these into their own workspace,
// and can re-add them after deleting. Examples illustrate the *type* of stock,
// not recommendations.

export const THESIS_LIBRARY = [
  {
    category: 'Live ideas',
    items: [
      { icon: '🛡️', name: 'SaaS the market left for dead', example_ticker: 'NOW',
        description: "Fear that AI agents make per-seat software obsolete has hit every enterprise software name alike. The bet: the strongest platforms, baked into how big companies run day to day, are being punished unfairly and recover as their results keep compounding.",
        cautious_criteria: 'Big AI deals slow down, margins keep shrinking, or the stock stays cheap for several quarters despite good results.',
        break_criteria: 'Customers actually start spending less because of AI — renewals fall or guidance gets cut.' },
      { icon: '🧬', name: 'Small-cap medical on the cusp', example_ticker: 'CAI',
        description: 'Smaller medical companies sitting on a valuable data set or platform right as everything scales at once — more customers, better insurance coverage, and new products arriving together.',
        cautious_criteria: 'Cash burn widens with no clear path to profit, insurance wins slow, or share sales flood the market.',
        break_criteria: 'A key clinical result disappoints, a flagship test loses coverage or FDA standing, or growth clearly stalls.' },
      { icon: '🚀', name: 'The SpaceX-IPO halo', example_ticker: 'RKLB',
        description: 'The first chance to buy SpaceX puts a spotlight on the whole public space sector and lifts the credible pure-plays with it — especially the main Western alternative for medium-size launches.',
        cautious_criteria: 'Valuation is already extreme and above analyst targets; space stocks swing wildly on mood.',
        break_criteria: "A flagship rocket's first launch fails or slips badly, or the SpaceX debut flops and drags the sector." },
      { icon: '⚡', name: 'AI infrastructure buildout', example_ticker: 'NVDA',
        description: 'The enormous spending to build AI — chips, networking, power, cooling — rewards the suppliers of the picks and shovels, no matter which AI app wins.',
        cautious_criteria: 'Cloud giants stop raising spending plans, or the gap between AI spending and AI revenue keeps widening.',
        break_criteria: 'A major cloud buyer cuts spending outright, or an efficiency breakthrough means the same AI needs far less hardware.' },
      { icon: '☢️', name: 'Nuclear & grid power', example_ticker: 'CEG',
        description: "AI data centers and electrification are driving a lasting jump in power demand with not enough supply — favoring nuclear (including small reactors) and the companies building the grid.",
        cautious_criteria: 'Power-demand forecasts get revised down, or borrowing costs squeeze these capital-heavy companies.',
        break_criteria: "A nuclear accident or regulatory reversal, or the demand surge never shows up in utilities' actual numbers." },
      { icon: '👟', name: 'Fallen global brand', example_ticker: 'NKE',
        description: 'A famous consumer brand at multi-year lows because of problems it created itself and can fix. The bet: the brand is too big and loved to stay down, and a credible turnaround pulls it back.',
        cautious_criteria: 'The turnaround keeps taking longer than promised, key markets stay weak, or margins stay squeezed.',
        break_criteria: 'The brand genuinely loses its cool factor — share losses turn permanent. Then it is a value trap, not a recovery.' },
    ],
  },
  {
    category: 'Quality & value classics',
    items: [
      { icon: '🔧', name: 'Turnaround / new management', example_ticker: 'NKE',
        description: "A good business that's currently broken, where a credible new leadership team is carrying out a specific fix the market hasn't believed yet.",
        cautious_criteria: 'Milestones slip, guidance keeps getting cut, or the turnaround drags past two or three years.',
        break_criteria: 'The core market is in permanent decline — no management team can fix a dying market.' },
      { icon: '✂️', name: 'Spin-off & sum-of-the-parts', example_ticker: 'GEV',
        description: 'A sprawling company is worth less whole than its pieces would be separately; a spin-off or breakup forces the market to value each part. Fresh spin-offs are routinely mispriced at first.',
        cautious_criteria: 'The breakup keeps getting delayed, or separation costs eat the value you hoped to unlock.',
        break_criteria: 'The "hidden gem" division is actually low quality, or debts and liabilities follow the valuable piece.' },
      { icon: '📣', name: 'Activist catalyst', example_ticker: 'LULU',
        description: 'An undervalued company where an activist investor is pushing for changes that unlock value — buybacks, a sale, a breakup, or new management.',
        cautious_criteria: "The activist's stake is small or toothless, management digs in, or a proxy fight drags on.",
        break_criteria: 'The activist gives up and sells, or the business gets worse faster than the changes can help.' },
      { icon: '🔄', name: 'Bottom of the cycle', example_ticker: 'MU',
        description: 'Buy a solid but cyclical company when earnings look awful and the stock looks expensive on those depressed earnings — right before the cycle turns. Memory chips, housing, chemicals, shipping.',
        cautious_criteria: 'The downturn keeps getting worse, inventories stay bloated, or demand shows no sign of turning.',
        break_criteria: 'What looked like a cycle is a permanent decline, or the company runs out of money before the upturn.' },
      { icon: '🏰', name: 'Quality compounder', example_ticker: 'COST',
        description: 'A high-quality business with a widening moat, strong returns on invested money, and a long runway to reinvest — buy at a fair price and let years of compounding work.',
        cautious_criteria: 'Returns slip, growth slows, or the valuation stretches well above its own history.',
        break_criteria: 'The moat gets breached by new tech or competition, or management starts wasting the cash.' },
      { icon: '⛏️', name: 'Picks and shovels', example_ticker: 'ASML',
        description: 'Instead of guessing which company wins a boom, own the supplier everyone in the boom has to buy from — the arms dealer to the gold rush.',
        cautious_criteria: "The boom's spending plans flatten, or big customers start making the supplier's product themselves.",
        break_criteria: 'The underlying boom stalls, or the supplier loses its technical edge and pricing power.' },
      { icon: '💲', name: 'Pricing power', example_ticker: '',
        description: 'Companies that can raise prices faster than their costs rise — strong brands, near-monopolies, must-have inputs — protect profits even when inflation bites.',
        cautious_criteria: 'Customers start buying less as prices rise (demand was not as locked-in as assumed).',
        break_criteria: 'A cheaper substitute appears, or regulators cap the pricing.' },
      { icon: '🛢️', name: 'Commodity shortage', example_ticker: 'CCJ',
        description: 'Years of under-investment in supply collide with rising demand, driving a multi-year price upswing that flows straight to producers — uranium, copper, oil, gold.',
        cautious_criteria: 'High prices lure new supply online, or demand softens with the economy.',
        break_criteria: 'A recession crushes demand, or a substitute/technology erases the shortage.' },
      { icon: '🧮', name: 'Paying down debt', example_ticker: '',
        description: 'A cash-generating company with too much debt steadily pays it down — and as debt shrinks, value shifts from lenders to shareholders and the stock re-rates higher.',
        cautious_criteria: 'Cash flow disappoints, refinancing comes at high rates, or loan terms tighten.',
        break_criteria: 'The business cannot generate enough cash to handle the debt — shareholders get diluted or wiped out.' },
      { icon: '💰', name: 'Returning cash to shareholders', example_ticker: '',
        description: 'A mature cash-rich business hands huge amounts back through buybacks and rising dividends; the shrinking share count lifts earnings per share even with flat revenue.',
        cautious_criteria: 'Buybacks slow, get funded with debt, or the core business is quietly eroding.',
        break_criteria: 'Cash flow falls and the generous returns prove unsustainable.' },
      { icon: '👵', name: 'Long-term demand wave', example_ticker: 'LLY',
        description: 'A durable trend playing out over decades — aging populations, obesity drugs, electrification — lifts the best-positioned companies regardless of the year-to-year economy.',
        cautious_criteria: 'The trade gets crowded and over-owned, or near-term adoption disappoints.',
        break_criteria: 'The trend proves smaller or slower than the story, or new technology reshuffles the winners.' },
      { icon: '🕸️', name: 'Winner-take-most network', example_ticker: '',
        description: "Every new user makes the product more valuable to everyone else, so the leader's advantage keeps widening until one or two players capture most of the profits.",
        cautious_criteria: "User or engagement growth slows, or regulators target the company's dominance.",
        break_criteria: 'A big platform shift (like AI) lets people route around the network entirely.' },
      { icon: '🏛️', name: 'Policy tailwind', example_ticker: '',
        description: 'A change in rules, subsidies, or government spending structurally favors a sector — reshoring incentives, defense budgets, deregulation.',
        cautious_criteria: 'The benefit is already priced in, or the implementation and funding stall.',
        break_criteria: 'The policy gets reversed after a political or leadership change.' },
      { icon: '🧩', name: 'Too complicated to value', example_ticker: '',
        description: 'A holding company or tangled business the market under-values simply because it is hard to model; the discount closes as the structure gets simpler or better understood.',
        cautious_criteria: 'The discount just sits there for years with no catalyst to close it.',
        break_criteria: 'The complexity is hiding real problems — bad divisions, conflicts of interest — not hidden value.' },
      { icon: '🩹', name: 'Thrown out with the bathwater', example_ticker: 'NOW',
        description: 'Indiscriminate selling — a sector dumped on a scary headline, index rebalancing, tax-loss season — pushes genuinely good companies below what they are worth.',
        cautious_criteria: 'The scary story has real teeth for some names in the group; do not buy the whole sector blindly.',
        break_criteria: 'For your specific pick, the feared disruption turns out to be real and permanent.' },
    ],
  },
  {
    category: 'Catalysts & signals',
    items: [
      { icon: '🗣️', name: 'Buzz before the news', example_ticker: '',
        description: 'A stock catching real attention on Reddit and social communities before analysts and mainstream press cover it — where the buzz traces to something checkable (a product, contract, improving numbers), not just hype.',
        cautious_criteria: 'Chatter rises but ties to nothing real, the stock is tiny and hard to trade, or it already shot up on the noise.',
        break_criteria: 'It is a coordinated pump or pure meme with no business behind it. High risk; keep it small.' },
      { icon: '💼', name: 'Insiders buying together', example_ticker: '',
        description: 'Several insiders — CEO, CFO, multiple directors — buying stock with their own money around the same time signals conviction from the people who know the business best.',
        cautious_criteria: 'It is one small purchase or option-related buying, and the stock keeps sliding anyway.',
        break_criteria: 'The fundamentals deteriorate regardless — insiders can be early, or simply wrong.' },
      { icon: '📈', name: 'Estimates keep rising', example_ticker: '',
        description: 'Analysts keep nudging forecasts higher and the company keeps beating; good news gets priced in slowly, so a steady stream of upgrades often continues. Ride the wave.',
        cautious_criteria: 'The streak of beats and raises narrows, or the stock stops reacting to good results.',
        break_criteria: 'A profit warning or big miss flips the estimate trend from rising to falling.' },
      { icon: '🩳', name: 'Short squeeze in the making', example_ticker: '',
        description: 'A heavily bet-against stock where the business is quietly getting better; a positive surprise forces short-sellers to buy back shares, adding fuel to the rally.',
        cautious_criteria: 'The heavy short interest is justified by real problems, or the squeeze setup is not as tight as it looks.',
        break_criteria: 'The bears are simply right — the hoped-for good news never comes. High risk.' },
      { icon: '🎯', name: 'Joining a big index', example_ticker: '',
        description: 'A company about to be added to a major index (like the S&P 500) gets a wave of forced buying from index funds, often building before and after the change.',
        cautious_criteria: 'The addition is already widely expected and baked into the price.',
        break_criteria: 'It gets passed over, or the business underneath does not justify the higher price once included.' },
      { icon: '⚙️', name: 'Profits about to inflect', example_ticker: '',
        description: 'Sales are growing past a mostly fixed cost base, so each extra dollar of revenue drops a big chunk straight to profit — earnings grow much faster than sales.',
        cautious_criteria: 'Costs creep up alongside revenue, or growth slows before profits inflect.',
        break_criteria: 'The business is actually cost-heavy on every sale, or its pricing erodes.' },
      { icon: '🦈', name: "Challenger eating the leader's lunch", example_ticker: 'ONON',
        description: "A smaller, faster company steadily taking market share from a slow incumbent — and the prize is the incumbent's entire market. The flip side of the fallen-brand trade.",
        cautious_criteria: 'Share gains slow down, or the incumbent fights back hard on price.',
        break_criteria: "The challenger's growth was a fad, or it cannot grow profitably." },
      { icon: '👤', name: 'Founder with skin in the game', example_ticker: '',
        description: 'Founder-CEOs who own a big chunk of the company think long-term and spend its money like owners. That alignment with shareholders has tended to pay off.',
        cautious_criteria: 'Governance is weak (super-voting shares used badly), or the founder is stretched thin.',
        break_criteria: "A key-person or succession shock, or the founder's big bets stop working." },
      { icon: '🏭', name: 'The herd thins out', example_ticker: '',
        description: 'In an oversupplied industry, weak players cut back or shut down; the survivors gain pricing power as supply tightens and demand recovers.',
        cautious_criteria: 'Capacity is not actually leaving, or new entrants and imports refill it.',
        break_criteria: "Demand falls faster than supply, or the slump outlasts the company's balance sheet." },
      { icon: '🤝', name: 'Merger arbitrage', example_ticker: '',
        description: 'Buy a company that has agreed to be acquired while it trades a little below the deal price; pocket the gap when the deal closes. Lower drama, with a defined finish line.',
        cautious_criteria: "The gap is wide because regulators or the buyer's financing look shaky.",
        break_criteria: 'The deal falls apart — the target usually drops back to or below its pre-offer price.' },
      { icon: '🤖', name: 'Using AI to fatten margins', example_ticker: '',
        description: 'Not the companies selling AI, but the ones using it to cut their own costs — automating service, operations, content. The demand side of AI, where productivity lands in profits.',
        cautious_criteria: 'AI spending rises but cost savings have not shown up in the margins yet.',
        break_criteria: 'AI cheapens their product or pricing faster than it cuts their costs.' },
      { icon: '🛣️', name: 'The toll road', example_ticker: '',
        description: 'A business in the middle of an essential flow — an exchange, railroad, pipeline, payment network — with steady, inflation-linked cash flows that are very hard to dislodge.',
        cautious_criteria: 'Regulators cap its pricing, or volumes tied to one cyclical market soften.',
        break_criteria: 'A new technology or rule change lets people route around the toll road.' },
      { icon: '🔁', name: 'Switching to subscriptions', example_ticker: '',
        description: 'A company moving from one-time sales to recurring subscription revenue; the market pays a higher multiple for predictable income, so the stock re-rates as the mix flips.',
        cautious_criteria: 'The switch stalls, or it eats near-term sales without clearly growing the recurring side.',
        break_criteria: 'Customers keep leaving — the recurring revenue is not actually sticky.' },
      { icon: '🧨', name: 'Buying what everyone hates', example_ticker: '',
        description: 'An entire unloved sector trades at rock-bottom valuations while still generating cash. You get paid to wait, or catch the upside when sentiment finally turns.',
        cautious_criteria: 'The sector is cheap for a real structural reason rather than a temporary one.',
        break_criteria: 'It is a melting ice cube — permanent decline, not a down cycle.' },
      { icon: '⚗️', name: 'One big event', example_ticker: '',
        description: 'A dated, high-impact event — a drug trial result, an FDA decision, a contract award, a court ruling — that could send the stock sharply one way. Attractive when the setup is lopsided in your favor.',
        cautious_criteria: 'The outcome is already widely expected, or the date keeps slipping.',
        break_criteria: 'The event goes against you. Genuinely all-or-nothing — size it small.' },
    ],
  },
  {
    category: 'More angles',
    items: [
      { icon: '🧱', name: 'Serial acquirer', example_ticker: '',
        description: 'A disciplined company that grows by repeatedly buying small businesses at good prices and running them well — compounding value through smart acquisitions year after year.',
        cautious_criteria: 'It starts overpaying, runs out of targets, or takes on too much debt to keep buying.',
        break_criteria: 'A big acquisition goes wrong, or the structure becomes too sprawling to manage.' },
      { icon: '🤝', name: 'A giant takes a stake', example_ticker: '',
        description: 'A smaller company gets a large strategic investment from a major industry player — validation, cash, and often customers, with the market re-rating on the endorsement.',
        cautious_criteria: 'The stake is small or purely financial, with no real partnership behind it.',
        break_criteria: 'The partnership never turns into revenue, or the big backer changes course.' },
      { icon: '🎯', name: 'A model rivals cannot copy', example_ticker: '',
        description: 'A newcomer built on a business model incumbents cannot match without hurting their own existing business — the bigger player is stuck watching because copying would cannibalize its cash cow.',
        cautious_criteria: 'The incumbent finds a way to respond without too much pain.',
        break_criteria: 'The edge turns out easy to copy after all, or the model cannot be made profitable.' },
      { icon: '📈', name: 'Hitting the steep part of the curve', example_ticker: '',
        description: 'A product reaching the fast-adoption stretch of its growth curve — past the early adopters and into mainstream uptake, where sales accelerate quickly.',
        cautious_criteria: 'Adoption starts slowing earlier than expected, or competitors crowd in.',
        break_criteria: 'The real market turns out smaller than the hype implied.' },
      { icon: '💎', name: 'Trading below what it owns', example_ticker: '',
        description: 'A stock priced below the value of its actual assets — cash, real estate, stakes in other companies. Buying a dollar of stuff for less than a dollar, with limited downside if the assets are real.',
        cautious_criteria: 'Management will not act to surface the value, or the assets are slowly losing worth.',
        break_criteria: 'The assets are worth less than they appear, or cash keeps getting burned.' },
      { icon: '💵', name: 'Fortress balance sheet', example_ticker: '',
        description: 'A company holding so much net cash that it covers a big slice of its market value — limiting the downside and giving firepower for buybacks, dividends, or acquisitions.',
        cautious_criteria: 'Management just sits on the cash and does nothing useful with it.',
        break_criteria: 'The core business burns through the cash pile over time.' },
      { icon: '💱', name: 'Weak-dollar winner', example_ticker: '',
        description: 'Companies that earn a lot abroad or export from the US get a tailwind when the dollar weakens — foreign earnings translate into more dollars.',
        cautious_criteria: 'The dollar move looks temporary, or currency hedges blunt the benefit.',
        break_criteria: 'The dollar strengthens again, or weak local economies offset the currency gain.' },
      { icon: '🌍', name: 'A country turns a corner', example_ticker: '',
        description: 'A whole national market re-rates as it undergoes real reform — better governance, falling rates, a stabilizing currency — lifting its better companies with it.',
        cautious_criteria: 'Reforms are promised but not delivered, or politics looks shaky.',
        break_criteria: 'The reform stalls or reverses, or the currency falls apart.' },
      { icon: '🎁', name: 'Getting a division for free', example_ticker: '',
        description: 'The market values a company entirely on its boring main business and assigns roughly zero to a promising side unit — if that unit delivers, you got it for nothing.',
        cautious_criteria: 'The hidden unit needs heavy investment for years before paying off.',
        break_criteria: 'The side bet fails, or the core weakens enough to matter more than the option.' },
      { icon: '🪪', name: 'Protected by a license', example_ticker: '',
        description: 'A business shielded by something hard to replicate — a government license, regulatory approval, spectrum rights, strong patents — keeping competitors out and protecting prices.',
        cautious_criteria: 'The protection is up for renewal or under regulatory review.',
        break_criteria: 'The license is lost, opened to competition, or made obsolete by new rules or technology.' },
      { icon: '🏗️', name: 'Lowest-cost wins', example_ticker: '',
        description: 'The cheapest producer in an industry can undercut everyone, take share through downturns, and still make money when rivals cannot — a durable grind toward dominance.',
        cautious_criteria: 'A competitor finds a structurally cheaper method, or input costs spike for everyone.',
        break_criteria: 'The cost advantage erodes, or a new technology resets the whole cost curve.' },
      { icon: '📊', name: 'Winners keep winning', example_ticker: '',
        description: 'Stocks already in strong uptrends often keep outperforming for a while — momentum is one of the most persistent patterns in markets. Ride strength rather than fight it.',
        cautious_criteria: 'The trend is stretched and crowded, or running on hype rather than results.',
        break_criteria: 'Momentum snaps — a sharp reversal can undo gains fast, so have an exit discipline. High risk.' },
    ],
  },
];
